# Generated by Django 3.2.9 on 2021-12-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_calendardate_calendartime_resource_resourceservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardate',
            name='date',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='calendartime',
            name='hour',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='calendartime',
            name='minute',
            field=models.CharField(max_length=2),
        ),
    ]
