# Generated by Django 3.2.9 on 2021-12-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20211229_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceservice',
            name='resource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.resource'),
        ),
        migrations.AlterField(
            model_name='resourceservice',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.service'),
        ),
    ]
