# Generated by Django 3.2.9 on 2021-12-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20211229_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendardate',
            name='month',
        ),
        migrations.RemoveField(
            model_name='calendardate',
            name='year',
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='date',
            field=models.DateField(),
        ),
    ]
