# Generated by Django 3.2.9 on 2021-12-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20211230_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceservice',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.resource'),
        ),
        migrations.AlterField(
            model_name='resourceservice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.service'),
        ),
    ]
