# Generated by Django 3.2.9 on 2021-12-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20211230_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceservice',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourceservice',
            name='resource',
            field=models.ManyToManyField(to='appointment.Resource'),
        ),
        migrations.RemoveField(
            model_name='resourceservice',
            name='service',
        ),
        migrations.AddField(
            model_name='resourceservice',
            name='service',
            field=models.ManyToManyField(to='appointment.Service'),
        ),
    ]
