# Generated by Django 3.2.9 on 2021-12-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20211230_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceservice',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourceservice',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.resource'),
        ),
        migrations.RemoveField(
            model_name='resourceservice',
            name='service',
        ),
        migrations.AddField(
            model_name='resourceservice',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.service'),
        ),
    ]
